version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    deploy:
      restart_policy:
        condition: on-failure
