version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs
    ports:
      - 3000:5000
    deploy:
      restart_policy:
        condition: on-failure
